sudo: required

language: go

env:
  global:
  - NAME=user

services:
  - docker

install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - helm init --client-only
  - helm plugin install https://github.com/chartmuseum/helm-push
  - go get github.com/mikefarah/yq
  - sudo apt-get install jq

script:
  - echo "Hi"

before_deploy:
  - yq write --inplace charts/$NAME/values.yaml image.tag "${TRAVIS_TAG}"
  - mkdir -p /tmp/charts
  - helm package charts/$NAME --version="${TRAVIS_TAG}" --dependency-update --destination /tmp/charts
  - helm repo add chartmuseum https://charts.containerum.io

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    verbose: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "/tmp/charts/$NAME-${TRAVIS_TAG}.tgz"
      - "/tmp/charts/index.yaml"
    skip_cleanup: true
    on:
      tags: true
