sudo: required

language: go

env:
  global:
  - IMAGE_NAME=containerum/mail

services:
  - docker

install:
  - go get github.com/mikefarah/yq
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - helm init --client-only
script:
  - helm repo index mail

before_deploy:
  - yq write --inplace mail/Chart.yaml appVersion "${TRAVIS_TAG}"

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      tags: true
