sudo: required

language: go

env:
  global:
  - NAME=user
  - IMAGE_NAME=containerum/mail
  - HELM_URL=https://kfeofantov.github.io/test-ci

services:
  - docker

install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - helm init --client-only

script:
  - echo "Hello!"

before_deploy:
  - helm package charts/$NAME --version="${TRAVIS_TAG}" --dependency-update --destination charts
  - helm repo index --url $HELM_URL --merge charts/index.yaml charts

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "charts/$NAME-${TRAVIS_TAG}.tgz"
      - "charts/index.yaml"
    skip_cleanup: true
    on:
      tags: true
