sudo: required

language: go

env:
  global:
  - IMAGE_NAME=containerum/mail
  - HELM_URL=https://kfeofantov.github.io/test-ci

services:
  - docker

install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - helm init --client-only

script:
  - echo "Hello!"

before_deploy:
  - helm package user --app-version="${TRAVIS_TAG}"
  - helm repo index --url $HELM_URL --merge index.yaml .

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      tags: true
