apiVersion: v1
entries:
  user:
  - apiVersion: v1
    appVersion: "1"
    created: 2018-05-17T18:55:35.858792794Z
    description: Containerum User service
    digest: 416d052c3c97c7929ba20a3b4ab0b6e183e5daefbc79bbb8803cbbb3321312a5
    name: user
    urls:
    - https://kfeofantov.github.io/test-ci/user-v1.0.0-rc10.tgz
    version: v1.0.0-rc10
generated: 2018-05-17T18:55:35.856961604Z
